version: "3.9"
services:
  frontend:
    container_name: FrontendApp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - warehouse_commonNetwork
  keycloak:
    container_name: keycloak_edgeapi
    image: quay.io/keycloak/keycloak:19.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    restart: always
    ports:
      - 8080:8080
    networks:
      - warehouse_commonNetwork
networks:
  warehouse_commonNetwork:
    external: true
